name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags:

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - name: swift-create-xcframework
        uses: segment-integrations/swift-create-xcframework@2.4.0
            
      # Create a release
      # Upload those artifacts to the release
